### ISSUE TITLE
Error in WDC - Script error. file: line: 0

### ISSUE THREAD

**Issue by gabrielroca** [starschema/tableau-web-table-connector#10]
Hi team,

Thanks for developping this, I need to connect to a SAP BO QaaWS and I am trying to use your WDC.

I follow up all the steps but I get an error once I open the http://localhost:3000/sapbo.html URL in Tableau WDC connector. 

Please find attached error below

![captura](https://cloud.githubusercontent.com/assets/24269924/20750538/b7fdaab8-b6f7-11e6-9db3-df6f32eb454f.PNG)

I am using Tableau 10.0 and the tableau-web-table-connector-tableau-10 code

I would be very grateful if you could help me on this as it is quite urgent for me

Many thanks!

**Comment by tfoldi** [comment]
are you using the tableau-10 branch? 

https://github.com/starschema/tableau-web-table-connector/tree/tableau-10

**Comment by endre-jenei** [comment]
Can we do a screensharing session to walk through the steps you've taken?

**Comment by gabrielroca** [comment]
Hi team 

We fixed it finally! There were some npm packages missing in my PC. Really appreciated your help!! 

Thanks very much!
