### ISSUE TITLE
Cannot GET /sapbo.html

### ISSUE THREAD

**Issue by QTarantella** [starschema/tableau-web-table-connector#4]
Hi all,
- i've correctly installed resources with the command: "npm install ./build-sap-bo.bat"
- i have correctly launched command "coffee coffee/sap_bo/proxy_server.coffee" using Nod.js.
-  i've port 3000 listening 

Why Tableau returns me "Cannot GET /sapbo.html" ?

Thanks

**Comment by tfoldi** [comment]
Hey, the correct command is:

```
npm install
```

and after the

```
./build-sap-bo.bat
```

Can you please upload the console output after these commands? 

Thanks

**Comment by tfoldi** [comment]
Hey, @QTarantella can you confirm that you still have the issue?

**Comment by tfoldi** [comment]
I close the ticket since there are not enough information to proceed. Feel free to reopen when you have your answers and the issue still persist
