### ISSUE TITLE
Business Objects connector Questions

### ISSUE THREAD

**Issue by cpare** [starschema/tableau-web-table-connector#5]
**Tableau 9.1 windows user trying to connect to Business Objects QAAWS**
The documentation had a few gaps I could have used some assistance with, considering I have never used any of the tools this project seems dependent on - below are the steps I took, and it looks like I am close, but not there 100% yet.  Please update the documentation to include these steps for the complete n00bs like myself.
- download node.js and install it (https://nodejs.org/en/) 
- Update NPM by typing "npm install npm -g"
- Install Coffee "npm install -g coffee-script" (CoffeeScript is a little language that compiles into JavaScript.)
- Download the tableau-web-table-connector zip, and extract into a directory
- Open a command shell as Administrator
- run "npm install" from the administrator command shell while in the extracted directory
- run "build-sap-bo.sh" from the administrator command shell while in the extracted directory
- run "coffee coffee/sap_bo/proxy_server.coffee" from the administrator command shell while in the extracted directory

**Once I get this working on my workstation, what needs to be done on our Tableau server to allow this to be refreshed on a schedule?**

**Comment by tfoldi** [comment]
hey, you should import the generated HTML file to the Tableau Server

https://onlinehelp.tableau.com/current/server/en-us/datasource_wdc.htm#importing

If you have 10 mins I can show it over webex

**Comment by cpare** [comment]
Thanks so much for this document, I am going to give it a shot in one of our lower environments once I can successfully query from my workstation - if I have any trouble I may take you up on your offer.
